var GAME_LEVELS = [
  ["                                                                                 ",
   "                                      x                                          ",
   "                                      x                                          ",
   "                                      x                                          ",
   "                                      x                                          ",
   "                                    o x                                          ",
   "        o                           xxx                                          ",
   "       xxxx   x  xxxx        xxxx                        xxxxxxxxx               ",
   "              x	    xxxx  xxxx   x       xx              x!!!!!!!x               ",
   "xxxx          x        !  !                               x!!!!!x                ",
   "              x        !  !         xx                     x!v!x                 ",
   "       xxxx   x        !  !                                                      ",
   "              x         oo      xx           o o                                 ",
   "xxxx          x                                                     oo           ",
   "              x     xxxxxxxxxx             xx   xx                xxxx   oo      ",
   "       xxxx   x                          xxxx   xxxx                   xxxx      ",
   "              x                xxxxxxxxxxxxxx   xxxxxxxxxxxxxx                 o ",
   "xxxx          x                                                                o ",
   "              x                                                                  ",
   "       xxxx   x                                                                  ",
   "  @           x                                                                  ",
   "xxxxxb        x                                                                  ",
   "              x                                                                  ",
   "!!!!!!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  [" !!!!!                                                                           ",
   " !   !                                                                           ",
   " ! @ !                                 ooo                                       ",
   " !   !                               xxxxxxx                                     ",
   " !   !                              xx  v  xx                                xxxx",
   " !   !                                                                       xvvx",
   " !   !                                     xxx                                  x",
   " !                                 xxx                xx =          = xx        x",
   " ! o                      o                      oo xxxxxxxxxxxxxxxxxxxxxxx oo  x",
   "xxxxxxx   xxxxxxxx  x    xxx    x  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  x",
   "                 x!!!!!!!!!!!!!!!!!x                                         !  x",
   "                 xxxxxxxxxxxxxxxxxxx                                         !  x",
   "                                                                             !  x",
   "                                            x  x                             !  x",
   "                                            x  x                             !  x",
   "                                            x  x                                x",
   "                                          x      x                              x",
   "                                           xx  xx                               x",
   "                                             xx                            xxxxxx",
   "                                                                      xxxxxx     ",
   "                                                                xxxxxxx          ",
   "                                             !!!!!!!!!!!!!!!!   x                ",
   "                       o        x|    |x     !!!!!!!!!!!!!!!!   x                ",
   "                    o        xxxxxxxxxxxxx                      x                ",
   "       ooooooooo                         x       ooooooo        x                ",
   "  xxxxxxxxxxxxxxxxxxxx                   xxxxxxxxxxxxxxxxxxxxxxxx                ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 "],
  ["                                                                                 ",
   "  @                         o                 o              o                   ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
   "                                                                          x      ",
   "                                                               ||||       x      ",
   "                                                              |    |      x      ",
   "x                                                            |      |     x      ",
   "x           oo                                       o      |        |    x      ",
   "x           xx              o     o                  x     |          |   x      ",
   "x          xxxx             x  o  x                 xxx                          ",
   "x         xxxxxx       x       x        x          xxxxx                         ",
   "x    xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                                            !!!!",
   "x                                                                      oo    vvvv",
   "xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        ",
   "                 x x       xxx    xxxxxxxxxx                                     ",
   "                 xxx        xx                                                   ",
   "                             x oo      oooooooo                                  ",
   "                             x oo xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!",
   "                               oo                                                ",
   "                                                                                 ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 "],
  ["  x                x       xxxxxxxxxxxxxxxxxxxx         x                          x                          ",
   "  x                x      x                    x        x                          x                          ",
   "   x              x      x                      x       x                          x                          ",
   "   x              x     x                        x      x                          x                          ",
   "    x           x      x     		@			  x     x                          x                          ",
   "    x           x      x                          x     x                          x                          ",
   "     xx       xx       x                          x     x                          x                          ",
   "       xxxxxxx         x    					  x     x                          x                          ",
   "          x            x 						  x     x                          x                          ",
   "          x            x            			  x     x                          x                          ",
   "          x            x!!!!!!!!!!!!!!!!!!!!!!!!!!x     x                          x                          ",
   "          x             x!!!!!!!!!!!!!!!!!!!!!!!!x      x                          x                          ",
   "          x              x!!!!!!!!!!!!!!!!!!!!!!x        x                        x                           ",
   "          x               x!!!!!!!!!!!!!!!!!!!!x          x                      x                            ",
   "          x                xxxxxxxxxxxxxxxxxxxx            xxxxxxxxxxxxxxxxxxxxxx                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "     x                                x   xxxxxxxxxxxxx   xxx                x       x     x                  ",
   "     x                                x         x         x xx               x       x	   x                  ",
   "      x                              x          x         x  xx              x       x     x                  ",
   "      x                              x          x         x   xx             x       x     x                  ",
   "       x                            x           x         x    xx            x       x     x                  ",
   "       x                            x           x         x     xx           x       x     x                  ",
   "        x                          x            x         x      xx          x       x     x                  ",
   "        x                          x            x         x       xx         x       x     x                  ",
   "         x                        x             x         x        xx        x       x     x                  ",
   "         x                        x             x         x         xx       x       x     x                  ",
   "          x                      x              x         x          xx      x       x     x                  ",
   "          x          xx          x              x         x           xx     x       x     x                  ",
   "           x        x  x        x               x         x            xx    x       x     x                  ",
   "           x        x  x        x               x         x             xx   x       x     x                  ",
   "            x      x    x      x                x         x              xx  x                                ",
   "            x      x    x      x	            x         x               xx x       x     x                  ",
   "             xxxxxx      xxxxxx           xxxxxxxxxxxxx   x                xxx       x     x                  "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
